#!/bin/bash
set +e

log() { echo "[$(date '+%H:%M:%S')] $*"; }
NTFY_TOPIC="${NTFY_TOPIC:-}"
ROOT_PASS="${ROOT_PASS:-}"
PORT="${PORT:-8080}"
NGROK_AUTHTOKEN="${NGROK_AUTHTOKEN:-}"
NGROK_DOMAIN_SSH="${NGROK_DOMAIN_SSH:-}"
LOGDIR="/tmp/ngrok"
mkdir -p "$LOGDIR"

log "=== NGROK TUNNEL MANAGER ==="

# ---- Stop helper ----
stop_pid() {
    local pidf="$1"
    test -f "$pidf" && kill "$(cat "$pidf")" 2>/dev/null
    rm -f "$pidf"
}

# ---- Add ngrok authtoken (needed before starting tunnels) ----
add_token() {
    test -n "$NGROK_AUTHTOKEN" || return 0
    ngrok config add-authtoken "$NGROK_AUTHTOKEN" >/dev/null 2>&1 && \
        log "✅ ngrok authtoken configured" || \
        log "⚠️ failed to configure ngrok authtoken"
}

# ---- Start one TCP tunnel, return public endpoint when known ----
start_tunnel() {
    local port="$1" label="$2"
    local logf="$LOGDIR/${port}.log"
    local pidf="$LOGDIR/${port}.pid"
    local url=""

    stop_pid "$pidf"
    sleep 1

    log "Starting ngrok tunnel $label on port $port..."
    ngrok tcp "$port" --log stdout --log-format json > "$logf" 2>&1 &
    echo "$!" > "$pidf"

    # Wait for the public endpoint to appear in ngrok logs
    for i in $(seq 1 30); do
        sleep 2
        url=$(jq -r 'select(.obj and .obj.url) | .obj.url' "$logf" 2>/dev/null | grep -v '^null$' | head -1)
        test -n "$url" && break
        url=$(grep -oP 'url=tcp://\K[0-9a-zA-Z.:-]+' "$logf" 2>/dev/null | head -1)
        test -n "$url" && break
    done

    if test -n "$url"; then
        log "  ✅ $label → ${url}"
    else
        log "  ⚠️ $label URL not found yet (will retry later)"
        url=$(tail -3 "$logf" 2>/dev/null | tr '\n' ' ')
    fi
    echo "$url"
}

# ---- Preconditions: no authtoken → tunnels cannot start ----
if test -z "$NGROK_AUTHTOKEN"; then
    log "⚠️ NGROK_AUTHTOKEN not set — tunnels disabled."
    log "   Set env NGROK_AUTHTOKEN (https://dashboard.ngrok.com/get-started/your-authtoken) and restart."
    while true; do sleep 60; done
fi

add_token

# ---- Start all tunnels ----
# SSH :22 gets a reserved domain if NGROK_DOMAIN_SSH is set, otherwise random TCP address
log "🚀 Starting ngrok tunnels..."

if test -n "$NGROK_DOMAIN_SSH"; then
    stop_pid "$LOGDIR/22.pid"; sleep 1
    log "Starting ngrok SSH tunnel on reserved domain $NGROK_DOMAIN_SSH..."
    ngrok tcp 22 --domain "$NGROK_DOMAIN_SSH" --log stdout --log-format json > "$LOGDIR/22.log" 2>&1 &
    echo "$!" > "$LOGDIR/22.pid"
    SSH_URL="$NGROK_DOMAIN_SSH"
    log "  ✅ SSH → ${SSH_URL}"
else
    SSH_URL=$(start_tunnel 22 "SSH")
fi
WEB_URL=$(start_tunnel 80 "WEB")
APP_URL=$(start_tunnel "$PORT" "APP")

# ---- Normalize endpoints to host:port ----
norm() {
    local u="$1"
    u="${u#tcp://}"
    echo "$u"
}
SSH_ENDPOINT=$(norm "$SSH_URL")
WEB_ENDPOINT=$(norm "$WEB_URL")
APP_ENDPOINT=$(norm "$APP_URL")

# ---- Send ntfy notification ----
NTFY_MSG="⚡ Rairu-Kun2 VPS Online!
━━━━━━━━━━━━━━━━━━━━
🔐 SSH: ssh root@${SSH_ENDPOINT:-N/A}
🔑 Password: ${ROOT_PASS:-<auto-generated, lihat log>}
🌐 Web UI: ${WEB_URL:-N/A}
📡 App: ${APP_URL:-N/A}
━━━━━━━━━━━━━━━━━━━━
💡 SSH Access:
   ssh root@${SSH_ENDPOINT:-<endpoint>} -p <PORT_DARI_ENDPOINT>

━━━━━━━━━━━━━━━━━━━━
powered by DevCulture ©2026"

send_ntfy() {
    curl -s --max-time 10 -X POST "https://ntfy.sh/$NTFY_TOPIC" \
        -H "Title: $1" -H "Priority: $2" -H "Tags: $3" \
        ${4:+-H "Markdown: yes"} -d "$5" >/dev/null 2>&1
}

if test -n "$NTFY_TOPIC"; then
    send_ntfy "⚡ Rairu-Kun2 VPS Online" "high" "computer,rocket,key" "" "$NTFY_MSG" \
        && log "📲 ntfy notification sent (topic: $NTFY_TOPIC)" \
        || log "⚠️ ntfy send failed (will retry on next status update)"
else
    log "⚠️ NTFY_TOPIC not set — notifications skipped. SSH endpoint: ${SSH_ENDPOINT}"
fi

# ---- Watch tunnels — restart if dead ----
while true; do
    sleep 30

    for entry in "22:SSH" "80:WEB" "${PORT:-8080}:APP"; do
        IFS=':' read -r p l <<< "$entry"
        pidf="$LOGDIR/${p}.pid"
        if test -f "$pidf"; then
            pid=$(cat "$pidf")
            if ! kill -0 "$pid" 2>/dev/null; then
                log "🔄 Restarting $l tunnel (port $p)..."
                if test "$p" = "22" && test -n "$NGROK_DOMAIN_SSH"; then
                    ngrok tcp 22 --domain "$NGROK_DOMAIN_SSH" --log stdout --log-format json >> "$LOGDIR/22.log" 2>&1 &
                    echo "$!" > "$pidf"
                else
                    start_tunnel "$p" "$l" > /dev/null
                fi
            fi
        fi
    done

    # Periodic status update every 5 min
    if test $((SECONDS % 300)) -lt 30 2>/dev/null; then
        UPTIME=$(uptime -p 2>/dev/null | sed 's/up //')
        RAM=$(free -m | awk '/Mem:/{printf "%sMB/%sMB", $3, $2}')
        DISK=$(df -h / | awk 'NR==2{printf "%s/%s", $3, $2}')
        LIVE_SSH=$(jq -r 'select(.obj and .obj.url) | .obj.url' "$LOGDIR/22.log" 2>/dev/null | grep -v '^null$' | tail -1)
        LIVE_SSH=${LIVE_SSH:-$SSH_ENDPOINT}

        STATUS_MSG="📊 Rairu-Kun2 Status Update
━━━━━━━━━━━━━━━━━━━━
⏱  Uptime: ${UPTIME}
💾 RAM: ${RAM}
💿 Disk: ${DISK}
🔐 SSH: ssh root@${LIVE_SSH}
━━━━━━━━━━━━━━━━━━━━"
        if test -n "$NTFY_TOPIC"; then
            send_ntfy "📊 Rairu-Kun2 Status" "default" "bar_chart" "" "$STATUS_MSG" &
        fi
    fi
done

# Keep alive (shouldn't reach here)
tail -f /dev/null
